#ddev-generated
# Simple template to demonstrate timescale-with-mongo-and-mysql-fdw
services:
  timescale-with-mongo-and-mysql-fdw:
    container_name: ddev-${DDEV_SITENAME}-timescale-with-mongo-and-mysql-fdw
    image: pajserb0y/timescale-with-mongo-fdw-and-mysql-fdw:latest
    # command: tail -f /dev/null
    networks: [default, ddev_default]
    ports:
      - "5433:5432"
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
      - ".:/mnt/ddev_config"
